type: object
properties:
  environment:
    $ref: ./EnvironmentStatus.yaml
  applications:
    type: array
    items:
      $ref: ./Status.yaml
  containers:
    type: array
    items:
      $ref: ./Status.yaml
  jobs:
    type: array
    items:
      $ref: ./Status.yaml
  databases:
    type: array
    items:
      $ref: ./Status.yaml
  helms:
    type: array
    items:
      $ref: ./Status.yaml
