post:
  summary: Deploy application
  description: You must provide a git commit id
  operationId: deployApplication
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Actions
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/DeployRequest.yaml
  responses:
    '202':
      description: Deploy application
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Status.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Operation is in progress
