get:
  summary: Get application status
  operationId: getApplicationStatus
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Main Calls
  responses:
    '200':
      description: Get status
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Status.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
