get:
  summary: Get advanced settings
  description: >
    Get list and values of the advanced settings of the application.

    Default values for each setting are available in [our
    documentation](https://hub.qovery.com/docs/using-qovery/configuration/advanced-settings/)
  operationId: getAdvancedSettings
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Configuration
  responses:
    '200':
      description: Advanced settings list
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationAdvancedSettings.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  summary: Edit advanced settings
  description: Edit advanced settings by returning table of advanced settings.
  operationId: editAdvancedSettings
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Configuration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ApplicationAdvancedSettings.yaml
  responses:
    '201':
      description: Updated advanced settings
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationAdvancedSettings.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
