delete:
  summary: Delete a secret from an application
  description: >
    - To delete a secret you must have the project user permission

    - You can't delete a BUILT_IN secret

    - If you delete a secret having override or alias, the associated
    override/alias will be deleted as well
  operationId: deleteApplicationSecret
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
    - $ref: ../components/parameters/secretId.yaml
  tags:
    - Application Secret
  responses:
    '204':
      $ref: ../components/responses/Deleted.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  summary: Edit a secret belonging to the application
  description: >
    - You can't edit a BUILT_IN secret

    - For an override, you can't edit the key

    - For an alias, you can't edit the value

    - An override can only have a scope lower to the secret it is overriding
    (hierarchy is BUILT_IN > PROJECT > ENVIRONMENT > APPLICATION)
  operationId: editApplicationSecret
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
    - $ref: ../components/parameters/secretId.yaml
  tags:
    - Application Secret
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SecretEditRequest.yaml
  responses:
    '200':
      description: Edited the secret value
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SecretResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
