get:
  summary: List application secrets
  description: >-
    Secrets are like environment variables, but they are secured and can't be
    revealed.
  operationId: listApplicationSecrets
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Secret
  responses:
    '200':
      description: List secrets
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SecretResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Add a secret to the application
  description: |
    - Add a secret to the application.
  operationId: createApplicationSecret
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Secret
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SecretRequest.yaml
  responses:
    '201':
      description: Add a secret
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SecretResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
