get:
  summary: Get Application Network information
  description: Get status of the application network settings.
  operationId: getApplicationNetwork
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Configuration
  responses:
    '200':
      description: Network information
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationNetworkResponse.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  summary: Edit Application Network
  description: Edit the Network settings of the application.
  operationId: editApplicationNetwork
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Configuration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ApplicationNetworkRequest.yaml
  responses:
    '201':
      description: Updated application network setting
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationNetworkResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
