post:
  summary: Reboot application
  operationId: rebootApplication
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Actions
  responses:
    '202':
      description: Application reboot has been requested
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Status.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Operation is in progress
