delete:
  summary: Delete an environment variable from an application
  description: >
    - To delete an environment variable from an application you must have the
    project user permission

    - You can't delete a BUILT_IN variable

    - If you delete a variable having override or alias, the associated
    override/alias will be deleted as well
  operationId: deleteApplicationEnvironmentVariable
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
    - $ref: ../components/parameters/environmentVariableId.yaml
  tags:
    - Application Environment Variable
  responses:
    '204':
      $ref: ../components/responses/Deleted.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  summary: Edit an environment variable belonging to the application
  description: >
    - You can't edit a BUILT_IN variable

    - For an override, you can't edit the key

    - For an alias, you can't edit the value

    - An override can only have a scope lower to the variable it is overriding
    (hierarchy is BUILT_IN > PROJECT > ENVIRONMENT > APPLICATION)
  operationId: editApplicationEnvironmentVariable
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
    - $ref: ../components/parameters/environmentVariableId.yaml
  tags:
    - Application Environment Variable
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/EnvironmentVariableEditRequest.yaml
  responses:
    '200':
      description: Edited the environment variable value
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentVariableResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
