put:
  summary: Edit a Custom Domain
  description: To edit a Custom Domain you must have the project user permission
  operationId: editCustomDomain
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
    - $ref: ../components/parameters/customDomainId.yaml
  tags:
    - Custom Domain
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CustomDomainRequest.yaml
  responses:
    '200':
      description: Edit a CustomDomain
      content:
        application/json:
          schema:
            $ref: ../components/schemas/CustomDomainResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
delete:
  summary: Delete a Custom Domain
  description: To delete an CustomDomain you must have the project user permission
  operationId: deleteCustomDomain
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
    - $ref: ../components/parameters/customDomainId.yaml
  tags:
    - Custom Domain
  responses:
    '204':
      $ref: ../components/responses/Deleted.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
