get:
  summary: List contributors
  operationId: listApplicationContributor
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
  tags:
    - Application Main Calls
  responses:
    '200':
      description: List application contributors
      content:
        application/json:
          schema:
            $ref: ../components/schemas/UserResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
