get:
  summary: Get Custom Domain status
  operationId: getCustomDomainStatus
  parameters:
    - $ref: ../components/parameters/applicationId.yaml
    - $ref: ../components/parameters/customDomainId.yaml
  tags:
    - Custom Domain
  responses:
    '200':
      description: Get status
      content:
        application/json:
          schema:
            $ref: ../components/schemas/CustomDomainResponse.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
