get:
  summary: List default cluster advanced settings
  description: >-
    Default values for each setting are available in [our
    documentation](https://hub.qovery.com/docs/using-qovery/configuration/cluster-advanced-settings/)
  operationId: getDefaultClusterAdvancedSettings
  tags:
    - Clusters
  responses:
    '200':
      description: Default cluster advanced settings
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ClusterAdvancedSettings.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
