get:
  summary: List environment deployment logs
  operationId: listEnvironmentLog
  description: This returns the last 1000 environment deployment logs.
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment Logs
  responses:
    '200':
      description: List logs
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentLogResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
