get:
  summary: Get environment statuses with stages
  operationId: getEnvironmentStatusesWithStages
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment Main Calls
  responses:
    '200':
      description: Get statuses with stages
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentStatusesWithStages.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
