get:
  summary: List environment secrets
  operationId: listEnvironmentSecrets
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment Secret
  responses:
    '200':
      description: List environment secrets
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SecretResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Add a secret to the environment
  description: |
    - Add a secret to the environment.
      - If the secret key already exists, then it will be replaced by the new one.
      - If the secret value points toward an existing secret key, it will be considered as an alias.
  operationId: createEnvironmentSecret
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment Secret
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/SecretRequest.yaml
  responses:
    '201':
      description: Added a secret
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SecretResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
