get:
  summary: List environment deployment logs v2
  operationId: listEnvironmentLogs
  description: This returns the last 1000 environment deployment logs v2
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
    - in: query
      name: version
      schema:
        type: string
  tags:
    - Environment Logs
  responses:
    '200':
      description: List logs v2
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentLogsResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
