get:
  summary: List eligible database types, versions and modes for the environment
  operationId: listEnvironmentDatabaseConfig
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Databases
  responses:
    '200':
      description: List eligible database
      content:
        application/json:
          schema:
            $ref: ../components/schemas/DatabaseConfigurationResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
