get:
  summary: List environment deployment stage
  operationId: ListEnvironmentDeploymentStage
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Deployment Stage Main Calls
  responses:
    '200':
      description: List deployment stage
      content:
        application/json:
          schema:
            $ref: ../components/schemas/DeploymentStageResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Create environment deployment stage
  operationId: CreateEnvironmentDeploymentStage
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Deployment Stage Main Calls
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/DeploymentStageRequest.yaml
  responses:
    '200':
      description: created deployment stage
      content:
        application/json:
          schema:
            $ref: ../components/schemas/DeploymentStageResponse.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
