get:
  summary: List applications
  operationId: listApplication
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
    - $ref: ../components/parameters/toUpdate.yaml
  tags:
    - Applications
  responses:
    '200':
      description: List applications
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Create an application
  operationId: createApplication
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Applications
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ApplicationRequest.yaml
  responses:
    '201':
      description: Create application
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Application name within the environment is already taken
