get:
  summary: List helms
  operationId: listHelms
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
    - $ref: ../components/parameters/toUpdate.yaml
  tags:
    - Helms
  responses:
    '200':
      description: List helms
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HelmResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Create a helm
  operationId: createHelm
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Helms
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/HelmRequest.yaml
  responses:
    '201':
      description: Create helm
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HelmResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Helm name within the environment is already taken
