get:
  summary: Get environment status
  operationId: getEnvironmentStatus
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment Main Calls
  responses:
    '200':
      description: Get status
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentStatus.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
