post:
  summary: Deploy environment
  description: >-
    This will deploy all the services of this environment to their latest
    version.
  operationId: deployEnvironment
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment Actions
  responses:
    '202':
      description: Deploy environment
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Status.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Operation is in progress
