get:
  summary: List all environment databases statuses
  description: Returns a list of databases with only their id and status.
  operationId: getEnvironmentDatabaseStatus
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Databases
  responses:
    '200':
      description: Get status
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ReferenceObjectStatusResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
