get:
  summary: List all environment applications statuses
  description: Returns a list of applications with only their id and status.
  operationId: getEnvironmentApplicationStatus
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Applications
  responses:
    '200':
      description: Get status
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ReferenceObjectStatusResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
