post:
  summary: Delete services
  description: Delete selected services
  operationId: deleteSelectedServices
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment Actions
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/EnvironmentServiceIdsAllRequest.yaml
  responses:
    '200':
      description: Services have been triggered to be deleted
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Operation is in progress
