post:
  summary: Deploy applications
  description: >-
    Start a deployment of the environment. Any of the services within the chosen
    environment based on the following rule: a service is deployed only if a new
    version is specified in the payload for that application/container or if
    there was a change in its configuration that needs to be applied (vCPU,RAM
    etc..)
  operationId: deployAllApplications
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Environment
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/DeployAllRequest.yaml
  responses:
    '202':
      description: Deployed applications
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Status.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Operation is in progress
