post:
  summary: Get helm default values
  operationId: createHelmDefaultValues
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Helms
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/HelmDefaultValuesRequest.yaml
  responses:
    '201':
      description: helm values
      content:
        text/plain:
          schema:
            type: string
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
