get:
  summary: List containers
  operationId: listContainer
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
    - $ref: ../components/parameters/toUpdate.yaml
  tags:
    - Containers
  responses:
    '200':
      description: List containers
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ContainerResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Create a container
  operationId: createContainer
  parameters:
    - $ref: ../components/parameters/environmentId.yaml
  tags:
    - Containers
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ContainerRequest.yaml
  responses:
    '201':
      description: Create container
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ContainerResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Container name within the environment is already taken
