get:
  summary: Get helm deployment restrictions
  description: Get helm deployment restrictions
  operationId: getHelmDeploymentRestrictions
  parameters:
    - $ref: ../components/parameters/helmId.yaml
  tags:
    - Helm Deployment Restriction
  responses:
    '200':
      description: Get helm deployment restrictions
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HelmDeploymentRestrictionResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Create a helm deployment restriction
  description: Create a helm deployment restriction
  operationId: createHelmDeploymentRestriction
  parameters:
    - $ref: ../components/parameters/helmId.yaml
  tags:
    - Helm Deployment Restriction
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/HelmDeploymentRestrictionRequest.yaml
  responses:
    '201':
      description: Added an helm deployment restriction
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HelmDeploymentRestrictionResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '409':
      description: >-
        A Helm deployment restriction with same properties already exists for
        this helm
