get:
  summary: Get advanced settings
  description: Get list and values of the advanced settings of the helm.
  operationId: getHelmAdvancedSettings
  parameters:
    - $ref: ../components/parameters/helmId.yaml
  tags:
    - Helm Configuration
  responses:
    '200':
      description: Advanced settings list
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HelmAdvancedSettings.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  summary: Edit advanced settings
  description: Edit advanced settings by returning table of advanced settings.
  operationId: editHelmAdvancedSettings
  parameters:
    - $ref: ../components/parameters/helmId.yaml
  tags:
    - Helm Configuration
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/HelmAdvancedSettings.yaml
  responses:
    '201':
      description: Updated advanced settings
      content:
        application/json:
          schema:
            $ref: ../components/schemas/HelmAdvancedSettings.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
