get:
  summary: Get job deployment restrictions
  description: Get job deployment restrictions
  operationId: getJobDeploymentRestrictions
  parameters:
    - $ref: ../components/parameters/jobId.yaml
  tags:
    - Job Deployment Restriction
  responses:
    '200':
      description: Get job deployment restrictions
      content:
        application/json:
          schema:
            $ref: ../components/schemas/JobDeploymentRestrictionResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Create a job deployment restriction
  description: Create a job deployment restriction
  operationId: createJobDeploymentRestriction
  parameters:
    - $ref: ../components/parameters/jobId.yaml
  tags:
    - Job Deployment Restriction
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/JobDeploymentRestrictionRequest.yaml
  responses:
    '201':
      description: Added an environment variable
      content:
        application/json:
          schema:
            $ref: ../components/schemas/JobDeploymentRestrictionResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '409':
      description: >-
        A Job deployment restriction with same properties already exists for
        this job
