post:
  summary: Import variables
  description: Import environment variables in a defined scope, with a defined visibility.
  operationId: importJobEnvironmentVariable
  parameters:
    - $ref: ../components/parameters/jobId.yaml
  tags:
    - Job Environment Variable
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/VariableImportRequest.yaml
  responses:
    '201':
      description: Import environment variables
      content:
        application/json:
          schema:
            $ref: ../components/schemas/VariableImportResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
