get:
  summary: List job deployments
  description: Returns the 20 last job deployments
  operationId: listJobDeploymentHistory
  parameters:
    - $ref: ../components/parameters/jobId.yaml
  tags:
    - Job Deployment History
  responses:
    '200':
      description: List deployment history
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/DeploymentHistoryJobPaginatedResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
