get:
  summary: Get cluster helm values for self managed installation
  operationId: getInstallationHelmValues
  parameters:
    - $ref: ../components/parameters/organizationId.yaml
    - $ref: ../components/parameters/clusterId.yaml
  tags:
    - Clusters
  responses:
    '200':
      description: Helm values
      content:
        application/x-yaml:
          schema:
            type: string
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
