get:
  summary: Get cluster kubeconfig
  operationId: getClusterKubeconfig
  parameters:
    - $ref: ../components/parameters/organizationId.yaml
    - $ref: ../components/parameters/clusterId.yaml
  tags:
    - Clusters
  responses:
    '200':
      description: Get kubeconfig of the cluster
      content:
        application/x-yaml:
          schema:
            type: string
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
put:
  summary: Edit cluster kubeconfig
  operationId: editClusterKubeconfig
  parameters:
    - $ref: ../components/parameters/organizationId.yaml
    - $ref: ../components/parameters/clusterId.yaml
  tags:
    - Clusters
  requestBody:
    content:
      application/x-yaml:
        schema:
          type: string
  responses:
    '204':
      description: edit kubeconfig of the cluster
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
