post:
  summary: Create an environment variable override at the project level
  description: >
    - Allows you to override at project level an environment variable that has a
    higher scope.

    - You only have to specify a value in the request body

    - The system will create a new environment variable at project level with
    the same key as the one corresponding to the variable id in the path

    - The response body will contain the newly created variable

    - Information regarding the overridden_variable will be exposed in the
    "overridden_variable" field of the newly created variable
  operationId: createProjectEnvironmentVariableOverride
  parameters:
    - $ref: ../components/parameters/projectId.yaml
    - $ref: ../components/parameters/environmentVariableId.yaml
  tags:
    - Project Environment Variable
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Value.yaml
  responses:
    '201':
      description: Create variable override
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentVariableResponse.yaml
    '400':
      description: >-
        Can't create an override on a higher scope. Overrides can only be
        created from one scope to a lower scope. Scope hierarchy is BUILT_IN >
        PROJECT > ENVIRONMENT > APPLICATION
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
