get:
  summary: List environments
  operationId: listEnvironment
  parameters:
    - $ref: ../components/parameters/projectId.yaml
  tags:
    - Environments
  responses:
    '200':
      description: List environments
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentResponseList.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
post:
  summary: Create an environment
  operationId: createEnvironment
  parameters:
    - $ref: ../components/parameters/projectId.yaml
  tags:
    - Environments
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/CreateEnvironmentRequest.yaml
  responses:
    '201':
      description: Create environment
      content:
        application/json:
          schema:
            $ref: ../components/schemas/EnvironmentResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/NotAuthorized.yaml
    '403':
      $ref: ../components/responses/Forbidden.yaml
    '404':
      $ref: ../components/responses/NotFound.yaml
    '409':
      description: Environment name within the project is already taken
